#!/bin/bash
# generate-memory-backup.sh
# Reads ~/.hermes/memories/{MEMORY,USER}.md and outputs formatted memory-backup.md
# to stdout.
#
# Usage:
#   ./generate-memory-backup.sh > ~/hermes-identity/memory-backup.md
#
# The script strips "N|" numbered-line prefixes, skips "§" separator lines,
# and groups content by source file.

MEMORY_FILE="$HOME/.hermes/memories/MEMORY.md"
USER_FILE="$HOME/.hermes/memories/USER.md"

echo "# Memory Backup"
echo "Generated: $(date +%Y-%m-%d) (cron identity sync)"
echo ""

format_file() {
  local f="$1"
  local section_title="$2"
  echo "## $section_title"
  echo ""
  if [ ! -f "$f" ]; then
    echo "_(not found)_"
    echo ""
    return
  fi
  sed 's/^[0-9][0-9]*|//' "$f" | while IFS= read -r line; do
    case "$line" in
      "§") echo "" ;;
      "") ;;
      *) echo "- $line" ;;
    esac
  done
  echo ""
}

format_file "$MEMORY_FILE" "Durable Facts (from built-in memory store)"
format_file "$USER_FILE" "User Profile"

echo "---"
echo "Generated by scripts/generate-memory-backup.sh (hermes-self-maintenance skill)"
